# Generated by Django 3.2.9 on 2021-11-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('imageUrl', models.CharField(max_length=255)),
                ('countryOfOrigin', models.CharField(max_length=128)),
                ('typicalMealTime', models.IntegerField()),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dateOfRating', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
