# Generated by Django 3.2.9 on 2021-11-14 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mealRatings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealrating',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealRatings.meal'),
        ),
    ]
