# Generated by Django 3.2.9 on 2021-11-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealRatings', '0002_alter_mealrating_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='typicalMealTime',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=128),
        ),
    ]
