# Generated by Django 3.2.9 on 2021-11-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealRatings', '0005_alter_meal_typicalmealtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='typicalMealTime',
            field=models.IntegerField(choices=[(1, 'Morning'), (2, 'Afternoon'), (3, 'Evening')]),
        ),
    ]
